webtalk_init -webtalk_dir /home/jam/Documents/1.Freelancer/inProgress/ReactionTimer/project_1/project_1.sim/sim_1/behav/xsim/xsim.dir/tb_controller_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue May 21 13:37:34 2024" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2021.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3247384" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "fe15acf0-70d5-435c-a484-0c99aa49d139" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "e26929bdaa214ab29af9cc05b9e22793" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "40" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 20.04.6 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2700.000 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 ms" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "4.48_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "116740_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1156229352 -regid "211562375_1777527455_210691717_048" -xml /home/jam/Documents/1.Freelancer/inProgress/ReactionTimer/project_1/project_1.sim/sim_1/behav/xsim/xsim.dir/tb_controller_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/jam/Documents/1.Freelancer/inProgress/ReactionTimer/project_1/project_1.sim/sim_1/behav/xsim/xsim.dir/tb_controller_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/jam/Documents/1.Freelancer/inProgress/ReactionTimer/project_1/project_1.sim/sim_1/behav/xsim/xsim.dir/tb_controller_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
