#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2021.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Tue May 21 13:34:38 PKT 2024
# SW Build 3247384 on Thu Jun 10 19:36:07 MDT 2021
#
# IP Build 3246043 on Fri Jun 11 00:30:35 MDT 2021
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab -wto e26929bdaa214ab29af9cc05b9e22793 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot tb_controller_behav xil_defaultlib.tb_controller -log elaborate.log"
xelab -wto e26929bdaa214ab29af9cc05b9e22793 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot tb_controller_behav xil_defaultlib.tb_controller -log elaborate.log

